apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}
  name: shipping
spec:
  ports:
{{- toYaml .Values.service.ports | nindent 2 }}
  selector:
    app_type: {{ .Values.labels.app_type }} 
