resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
restartPolicy: Always
image:
  repo: pullapantangi
  tag: latest
  name: robo_user
labels:
  app_type: user
imagePullPolicy: Always
service:
  ports:
  - name: user
    port: 8080
    targetPort: 8080
