resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
restartPolicy: Always
image:
  repo: pullapantangi
  tag: latest
  name: ecomm_mongo
labels:
  app_type: mongodb
imagePullPolicy: Always
service:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
