affinity:
  key: "kubernetes.io/hostname"
  operator: In
  value: docker-desktop
image:
  repository: pullapantangi
  image: k8s_web
  tag: v1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 500Mi
serviceLabels:
   app_type: web
   resourceType: service
selectorLabels:
   type: fronend-web
#   app: roboshop
#   type: fronend-web
#   run: alma
port_80:
  - name: http
    port: 80 
    protocol: TCP
    targetPort: 80 
    nodePort: 30001
port_443:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
    nodePort: 30002 
service:   
  type: NodePort
https:
  disabled: true
replicaCount: 1
